// Generated by scripts/gen_agent_paths.py from src/ptc_agent/core/paths.py.
// Do not edit: run `uv run python scripts/gen_agent_paths.py` instead. The
// unit test tests/unit/core/test_sandbox_layout.py regenerates and diffs this
// file, so an edit here fails CI rather than silently diverging.

/** Working directory of the stock sandbox image. */
export const SANDBOX_ROOT = '/home/workspace';

/** Every root a sandbox path may be spelled with, current one first.
 *  Rootless form (no leading slash), callers strip that first. */
export const SANDBOX_ROOT_PREFIXES = [
  'home/workspace/',
  'home/daytona/',
] as const;

// Root-relative directories the path classifier keys off.
export const MEMORY_USER_DIR = '.agents/user/memory';
export const MEMORY_WORKSPACE_DIR = '.agents/memory';
export const MEMO_USER_DIR = '.agents/user/memo';
export const USER_PROFILE_DIR = '.agents/user/profile';
export const SKILLS_DIR = '.agents/skills';
export const THREADS_DIR = '.agents/threads';
export const LARGE_TOOL_RESULTS_DIR = '.agents/large_tool_results';
export const AGENTS_DIR = '.agents';
export const INTERNAL_DIR = '_internal';

export const MEMORY_INDEX_FILENAME = 'memory.md';
export const MEMO_INDEX_FILENAME = 'memo.md';

/** The three virtual JSON files that UserDataBackend serves. */
export const USER_PROFILE_FILES = {
  portfolio: 'portfolio.json',
  watchlist: 'watchlist.json',
  preference: 'preference.json',
} as const;

/** Agent-infrastructure dirs at the sandbox root, collapsed by
 *  default in the file panel. Source: AGENT_SYSTEM_DIRS. */
export const AGENT_SYSTEM_DIRS = [
  '.agents',
  '.self-improve',
  '.system',
  'mcp_servers',
] as const;

/** Root dirs an earlier layout owned, still present in a sandbox
 *  reused across its migration: `tools` moved under `_internal` in
 *  v4, `code` under `.system` in v2. A name-based filter needs them
 *  alongside AGENT_SYSTEM_DIRS. */
export const LEGACY_ROOT_TOOLS_DIR = 'tools';
export const LEGACY_ROOT_CODE_DIR = 'code';
export const LEGACY_ROOT_DIRS = [
  'code',
  'tools',
] as const;
