"""The routing ruleset: ordering policy, table lookup, and loading."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest
import yaml

from market_protocol.routing import (
    RULESET_VERSION,
    Cell,
    CellKey,
    ProbedProvider,
    ProviderInfo,
    Ruleset,
    RoutingTable,
    Surface,
    load_ruleset,
    order_providers,
)
from market_protocol.routing.ruleset import MIN_CALLS_PER_MINUTE_FOR_BARS

NOW =datetime(2026, 9, 9, 12, 0, tzinfo=timezone.utc)


def _probe(name: str, **kw) -> ProbedProvider:
    kw.setdefault("coverage_hit", 2)
    kw.setdefault("coverage_total", 2)
    return ProbedProvider(name=name, **kw)


def _cell(key: CellKey, providers: list[ProbedProvider]) -> Cell:
    return Cell(key=key, probed_at=NOW, providers=order_providers(key.surface, providers))


INTRADAY_1M = CellKey(market="cn", asset_class="equity", surface=Surface.INTRADAY, interval="1m")
LOGGER = "market_protocol.routing.ruleset"

# Written by hand, not dumped from the model, so a schema change that would
# strand files already on disk fails here rather than round-tripping clean.
V2_RULESET = """\
# Generated by a routing probe. Do not edit by hand;
version: 2
generated_at: '2026-09-10T06:09:16.631249Z'
probe_version: 1
providers:
  fmp:
    configured: true
    fingerprint: abcd1234
  tushare:
    configured: true
    fingerprint: null
cells:
- key:
    market: cn
    asset_class: equity
    surface: intraday
    interval: ohlcv-1m
  probed_at: '2026-09-10T05:59:12.615343Z'
  phase_at_probe: open
  canaries:
  - 600519.SH
  providers:
  - name: tushare
    entitled: true
    coverage_hit: 1
    coverage_total: 1
    session_complete: true
    anchors_ok: true
    lag_s: 30
    tier: realtime
    calls_per_minute: 500
    cost_calls: 1
    price_treatment: raw
    excluded_reason: null
    notes: []
  - name: fmp
    coverage_hit: 1
    coverage_total: 1
    lag_s: 600
    tier: delayed_15m
    notes:
    - https://example.com/bars?from=1&limit=5000
  - name: yfinance
    coverage_hit: 1
    coverage_total: 1
    session_complete: false
    excluded_reason: incomplete_session
- key:
    market: cn
    asset_class: equity
    surface: daily
    interval: null
  probed_at: '2026-09-10T07:30:00Z'
  phase_at_probe: closed
  providers:
  - name: tushare
    coverage_hit: 1
    coverage_total: 1
    price_treatment: dividend_adjusted
  - name: fmp
    coverage_hit: 1
    coverage_total: 1
    price_treatment: raw
- key:
    market: cn
    asset_class: equity
    surface: snapshot
    interval: null
  probed_at: '2026-09-10T05:59:12.615343Z'
  phase_at_probe: open
  providers:
  - name: fmp
    coverage_hit: 1
    coverage_total: 1
    lag_s: 600
    tier: delayed_15m
  - name: tushare
    coverage_hit: 1
    coverage_total: 1
    lag_s: 30
    tier: realtime
"""


def _write_ruleset(ruleset: Ruleset, path: Path) -> Path:
    """Write *ruleset* as a probe would; where and how it lands is the deployment's concern."""
    path.write_text(yaml.safe_dump(ruleset.model_dump(mode="json"), sort_keys=False))
    return path


# ---------------------------------------------------------------------------
# Policy
# ---------------------------------------------------------------------------

class TestOrderProviders:
    def test_not_entitled_is_excluded(self):
        out = order_providers(Surface.DAILY, [_probe("a", entitled=False), _probe("b")])
        assert [p.name for p in out] == ["b", "a"]
        assert out[1].excluded_reason == "not_entitled"

    def test_no_coverage_is_excluded(self):
        out = order_providers(Surface.DAILY, [_probe("a", coverage_hit=0), _probe("b")])
        assert {p.name: p.excluded_reason for p in out} == {"a": "no_coverage", "b": None}

    def test_incomplete_session_excluded_for_bars_only(self):
        bars = order_providers(Surface.INTRADAY, [_probe("a", session_complete=False)])
        assert bars[0].excluded_reason == "incomplete_session"
        snaps = order_providers(Surface.SNAPSHOT, [_probe("a", session_complete=False)])
        assert snaps[0].excluded_reason is None

    def test_bad_anchors_excluded(self):
        out = order_providers(Surface.INTRADAY, [_probe("a", anchors_ok=False)])
        assert out[0].excluded_reason == "bad_anchors"

    def test_quota_below_floor_excluded_for_bars_only(self):
        bars = order_providers(Surface.INTRADAY, [_probe("a", calls_per_minute=1)])
        assert bars[0].excluded_reason == "quota_below_floor"
        snaps = order_providers(Surface.SNAPSHOT, [_probe("a", calls_per_minute=1)])
        assert snaps[0].excluded_reason is None

    def test_measured_lag_outranks_declared_tier(self):
        out = order_providers(
            Surface.INTRADAY,
            [_probe("slow", lag_s=600, tier="realtime"), _probe("fast", lag_s=10, tier="delayed_15m")],
        )
        assert [p.name for p in out] == ["fast", "slow"]

    def test_ties_keep_probe_order(self):
        out = order_providers(Surface.DAILY, [_probe("a", tier="eod"), _probe("b", tier="eod")])
        assert [p.name for p in out] == ["a", "b"]

    def test_excluded_always_rank_last(self):
        out = order_providers(
            Surface.DAILY, [_probe("dead", entitled=False, lag_s=0), _probe("live", lag_s=300)]
        )
        assert [p.name for p in out] == ["live", "dead"]

    def test_input_is_not_mutated(self):
        original = _probe("a", entitled=False)
        order_providers(Surface.DAILY, [original])
        assert original.excluded_reason is None

    def test_a_feed_measured_past_the_delayed_ceiling_ranks_below_a_delayed_one(self):
        # Declared realtime but measured at 20 minutes: ranked by what it did,
        # which is end-of-day freshness, not by what it claims.
        out = order_providers(
            Surface.INTRADAY,
            [_probe("stale", lag_s=1200, tier="realtime"), _probe("delayed", lag_s=120, tier="delayed_15m")],
        )
        assert [p.name for p in out] == ["delayed", "stale"]

    @pytest.mark.parametrize("declared", [None, "delayed_15m"])
    def test_a_measured_live_feed_outranks_an_unmeasured_realtime_claim(self, declared):
        out = order_providers(
            Surface.INTRADAY,
            [_probe("claimed", tier="realtime"), _probe("measured", lag_s=10, tier=declared)],
        )
        assert [p.name for p in out] == ["measured", "claimed"]

    def test_quota_outranks_cost(self):
        out = order_providers(
            Surface.INTRADAY,
            [_probe("cheap", calls_per_minute=50, cost_calls=1),
             _probe("roomy", calls_per_minute=500, cost_calls=4)],
        )
        assert [p.name for p in out] == ["roomy", "cheap"]

    def test_equal_lag_prefers_more_calls_per_minute(self):
        out = order_providers(
            Surface.INTRADAY,
            [_probe("tight", lag_s=30, calls_per_minute=50), _probe("roomy", lag_s=30, calls_per_minute=500)],
        )
        assert [p.name for p in out] == ["roomy", "tight"]

    # Each default below is pinned by pairing an unset provider with a set one,
    # so moving the default either way reorders the pair.

    def test_an_undeclared_treatment_ranks_with_raw_on_daily(self):
        out = order_providers(
            Surface.DAILY,
            [_probe("raw", lag_s=300, price_treatment="raw"),
             _probe("undeclared", lag_s=10),
             _probe("adjusted", lag_s=600, price_treatment="dividend_adjusted")],
        )
        assert [p.name for p in out] == ["adjusted", "undeclared", "raw"]

    def test_neither_lag_nor_tier_ranks_below_an_eod_claim(self):
        out = order_providers(Surface.INTRADAY, [_probe("unknown"), _probe("eod", tier="eod")])
        assert [p.name for p in out] == ["eod", "unknown"]

    def test_an_unstated_quota_ranks_as_unlimited(self):
        out = order_providers(
            Surface.INTRADAY, [_probe("stated", calls_per_minute=100_000), _probe("unstated")]
        )
        assert [p.name for p in out] == ["unstated", "stated"]

    def test_a_quota_at_the_floor_stays_routable(self):
        (at_floor,) = order_providers(
            Surface.INTRADAY, [_probe("a", calls_per_minute=MIN_CALLS_PER_MINUTE_FOR_BARS)]
        )
        assert at_floor.routable
        (below,) = order_providers(
            Surface.INTRADAY, [_probe("a", calls_per_minute=MIN_CALLS_PER_MINUTE_FOR_BARS - 1)]
        )
        assert below.excluded_reason == "quota_below_floor"

    def test_a_feed_stamped_hours_ahead_ranks_with_no_lag_and_no_tier(self):
        # Local time read as UTC: eight hours "ahead", recorded with the realtime
        # class that lag earns, so neither may outrank an honest feed.
        out = order_providers(
            Surface.INTRADAY,
            [_probe("ahead", lag_s=-28800, tier="realtime"),
             _probe("eod", tier="eod"),
             _probe("delayed", lag_s=600, tier="delayed_15m")],
        )
        assert [p.name for p in out] == ["delayed", "eod", "ahead"]

    @pytest.mark.parametrize("lag_s,first", [(-60, "skewed"), (-61, "honest")])
    def test_seconds_of_clock_skew_still_count_as_a_measurement(self, lag_s, first):
        out = order_providers(
            Surface.INTRADAY,
            [_probe("honest", lag_s=30, tier="realtime"), _probe("skewed", lag_s=lag_s, tier="realtime")],
        )
        assert out[0].name == first

    def test_daily_ranks_adjusted_series_above_raw(self):
        raw = _probe("fmp", session_complete=True, tier="delayed_15m", price_treatment="raw", cost_calls=1)
        qfq = _probe("tushare", session_complete=True, tier="eod", price_treatment="dividend_adjusted",
                     cost_calls=4)
        assert [p.name for p in order_providers(Surface.DAILY, [raw, qfq])] == ["tushare", "fmp"]
        # Intraday does not weigh adjustment: the cheaper, fresher raw feed wins.
        assert [p.name for p in order_providers(Surface.INTRADAY, [raw, qfq])] == ["fmp", "tushare"]

    def test_surface_value_applies_the_same_policy(self):
        raw = _probe("fmp", lag_s=10, tier="realtime", price_treatment="raw")
        qfq = _probe("tushare", tier="eod", price_treatment="split_adjusted")
        assert [p.name for p in order_providers("daily", [raw, qfq])] == ["tushare", "fmp"]
        assert order_providers("snapshot", [_probe("a", calls_per_minute=1)])[0].excluded_reason is None
        with pytest.raises(ValueError):
            order_providers("nonsense", [raw])

    def test_daily_adjustment_outranks_a_fresher_measured_feed(self):
        raw = _probe("fmp", lag_s=10, tier="realtime", price_treatment="raw", calls_per_minute=300)
        qfq = _probe("tushare", tier="eod", price_treatment="split_adjusted", calls_per_minute=50)
        assert [p.name for p in order_providers(Surface.DAILY, [raw, qfq])] == ["tushare", "fmp"]

    def test_throttled_to_zero_rows_reads_quota_not_coverage(self):
        throttled = _probe("tushare", coverage_hit=0, coverage_total=3, calls_per_minute=1)
        (p,) = order_providers(Surface.INTRADAY, [throttled])
        assert p.excluded_reason == "quota_below_floor"


# ---------------------------------------------------------------------------
# RoutingTable
# ---------------------------------------------------------------------------

class TestRoutingTable:
    def test_returns_routable_names_in_order(self):
        rs = Ruleset(
            generated_at=NOW,
            cells=[_cell(INTRADAY_1M, [_probe("yfinance", session_complete=False), _probe("fmp")])],
        )
        assert RoutingTable(rs).order_for("intraday", "cn", "equity", "1m") == ["fmp"]

    def test_unknown_cell_is_none(self):
        rs = Ruleset(generated_at=NOW, cells=[_cell(INTRADAY_1M, [_probe("fmp")])])
        table = RoutingTable(rs)
        assert table.order_for("intraday", "us", "equity", "1m") is None
        assert table.order_for("daily", "cn", "equity") is None

    def test_interval_falls_back_to_interval_less_cell(self):
        key = CellKey(market="cn", asset_class="equity", surface=Surface.INTRADAY)
        rs = Ruleset(generated_at=NOW, cells=[_cell(key, [_probe("fmp")])])
        assert RoutingTable(rs).order_for("intraday", "cn", "equity", "15m") == ["fmp"]

    def test_exact_interval_wins_over_fallback(self):
        generic = CellKey(market="cn", asset_class="equity", surface=Surface.INTRADAY)
        rs = Ruleset(
            generated_at=NOW,
            cells=[_cell(generic, [_probe("fmp")]), _cell(INTRADAY_1M, [_probe("tushare")])],
        )
        table = RoutingTable(rs)
        assert table.order_for("intraday", "cn", "equity", "1m") == ["tushare"]
        assert table.order_for("intraday", "cn", "equity", "5m") == ["fmp"]

    def test_unprobed_interval_takes_the_nearest_probed_cell(self):
        five = CellKey(market="cn", asset_class="equity", surface=Surface.INTRADAY, interval="5m")
        rs = Ruleset(
            generated_at=NOW,
            cells=[_cell(INTRADAY_1M, [_probe("tushare")]), _cell(five, [_probe("fmp")])],
        )
        table = RoutingTable(rs)
        # 4h: widest probed bar no wider than it is 5m.
        assert table.order_for("intraday", "cn", "equity", "4h") == ["fmp"]
        # 1s: readable but narrower than every probed cell, so the narrowest governs.
        assert table.order_for("intraday", "cn", "equity", "1s") == ["tushare"]
        # 30s is not a schema width: unreadable, so no order.
        assert table.order_for("intraday", "cn", "equity", "30s") is None
        assert table.order_for("intraday", "hk", "equity", "4h") is None

    def test_a_month_is_not_read_as_a_minute(self):
        rs = Ruleset(generated_at=NOW, cells=[_cell(INTRADAY_1M, [_probe("tushare")])])
        table = RoutingTable(rs)
        assert table.order_for("intraday", "cn", "equity", "1m") == ["tushare"]
        assert table.order_for("intraday", "cn", "equity", "1M") is None

    def test_cell_with_everything_excluded_is_an_empty_list(self):
        rs = Ruleset(generated_at=NOW, cells=[_cell(INTRADAY_1M, [_probe("fmp", entitled=False)])])
        assert RoutingTable(rs).order_for("intraday", "cn", "equity", "1m") == []

    def test_surface_accepts_the_enum(self):
        rs = Ruleset(generated_at=NOW, cells=[_cell(INTRADAY_1M, [_probe("fmp")])])
        assert RoutingTable(rs).order_for(Surface.INTRADAY, "cn", "equity", "1m") == ["fmp"]


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

class TestLoadRuleset:
    def test_save_load_roundtrip(self, tmp_path):
        rs = Ruleset(
            generated_at=NOW,
            providers={"fmp": ProviderInfo(fingerprint="abcd1234")},
            cells=[_cell(INTRADAY_1M, [_probe("fmp", lag_s=12, tier="realtime")])],
        )
        path = _write_ruleset(rs, tmp_path / "data_routing.yaml")
        loaded = load_ruleset(path)
        assert loaded is not None
        assert loaded.providers["fmp"].fingerprint == "abcd1234"
        assert loaded.cells[0].key == INTRADAY_1M
        assert loaded.cells[0].providers[0].lag_s == 12

    def test_missing_file_is_none(self, tmp_path):
        assert load_ruleset(tmp_path / "nope.yaml") is None

    def test_unreadable_file_is_none(self, tmp_path):
        path = tmp_path / "data_routing.yaml"
        path.write_text("cells: [ this is not a ruleset\n")
        assert load_ruleset(path) is None

    def test_wrong_shape_is_none(self, tmp_path):
        path = tmp_path / "data_routing.yaml"
        path.write_text(f"version: {RULESET_VERSION}\ngenerated_at: '2026-09-09T12:00:00Z'\ncells: 7\n")
        assert load_ruleset(path) is None

    def test_version_mismatch_is_none(self, tmp_path):
        rs = Ruleset(generated_at=NOW, cells=[_cell(INTRADAY_1M, [_probe("fmp")])])
        path = _write_ruleset(rs, tmp_path / "data_routing.yaml")
        path.write_text(path.read_text().replace(f"version: {RULESET_VERSION}", "version: 99", 1))
        assert load_ruleset(path) is None

    def test_interval_is_stored_as_the_schema_id(self):
        assert INTRADAY_1M.interval == "ohlcv-1m"
        assert CellKey(market="cn", asset_class="equity", surface=Surface.INTRADAY,
                       interval="1min") == INTRADAY_1M

    def test_version_1_file_migrates_its_bare_intervals(self, tmp_path):
        path = tmp_path / "data_routing.yaml"
        path.write_text(
            "version: 1\n"
            "generated_at: '2026-09-09T12:00:00Z'\n"
            "cells:\n"
            "- key: {market: cn, asset_class: equity, surface: intraday, interval: 5m}\n"
            "  probed_at: '2026-09-09T12:00:00Z'\n"
            "  providers:\n"
            "  - {name: fmp, coverage_hit: 2, coverage_total: 2}\n"
        )
        loaded = load_ruleset(path)
        assert loaded is not None and loaded.version == RULESET_VERSION
        assert loaded.cells[0].key.interval == "ohlcv-5m"
        assert RoutingTable(loaded).order_for("intraday", "cn", "equity", "5min") == ["fmp"]

    def test_a_hand_written_version_2_file_routes_in_its_written_order(self, tmp_path):
        path = tmp_path / "data_routing.yaml"
        path.write_text(V2_RULESET)
        loaded = load_ruleset(path)
        assert loaded is not None and loaded.version == 2
        assert loaded.providers["fmp"].fingerprint == "abcd1234"
        assert [c.phase_at_probe for c in loaded.cells] == ["open", "closed", "open"]
        assert loaded.cells[0].providers[1].notes == ["https://example.com/bars?from=1&limit=5000"]
        table = RoutingTable(loaded)
        assert table.order_for("intraday", "cn", "equity", "1m") == ["tushare", "fmp"]
        assert table.order_for("daily", "cn", "equity") == ["tushare", "fmp"]
        # The policy would put tushare first here; the file's order is what routes.
        snapshot = loaded.cells[2]
        assert [p.name for p in order_providers(snapshot.key.surface, snapshot.providers)] == [
            "tushare", "fmp",
        ]
        assert table.order_for("snapshot", "cn", "equity") == ["fmp", "tushare"]

    def test_a_str_path_loads(self, tmp_path):
        path = tmp_path / "data_routing.yaml"
        path.write_text(V2_RULESET)
        loaded = load_ruleset(str(path))
        assert loaded is not None and len(loaded.cells) == 3

    def test_a_directory_is_none(self, tmp_path, caplog):
        with caplog.at_level("WARNING", logger=LOGGER):
            assert load_ruleset(tmp_path) is None
        assert "data_routing.ruleset.unreadable" in caplog.text

    def test_a_missing_version_is_none(self, tmp_path, caplog):
        path = tmp_path / "data_routing.yaml"
        path.write_text("generated_at: '2026-09-09T12:00:00Z'\ncells: []\n")
        with caplog.at_level("WARNING", logger=LOGGER):
            assert load_ruleset(path) is None
        assert "data_routing.ruleset.unreadable" in caplog.text and "version" in caplog.text

    def test_an_unknown_version_is_a_mismatch_even_when_its_cells_do_not_validate(
        self, tmp_path, caplog
    ):
        path = tmp_path / "data_routing.yaml"
        path.write_text(
            "version: 3\n"
            "generated_at: '2026-09-09T12:00:00Z'\n"
            "cells:\n"
            "- key: {market: cn, asset_class: option, surface: greeks}\n"
        )
        with caplog.at_level("INFO", logger=LOGGER):
            assert load_ruleset(path) is None
        (record,) = caplog.records
        assert record.getMessage().startswith("data_routing.ruleset.version_mismatch")
        assert "file=3" in record.getMessage()

    def test_anchors_and_aliases_are_refused(self, tmp_path, caplog):
        path = tmp_path / "data_routing.yaml"
        path.write_text(
            f"version: {RULESET_VERSION}\n"
            "generated_at: '2026-09-09T12:00:00Z'\n"
            "cells:\n"
            "- &cell\n"
            "  key: {market: cn, asset_class: equity, surface: daily}\n"
            "  probed_at: '2026-09-09T12:00:00Z'\n"
            "- *cell\n"
        )
        with caplog.at_level("WARNING", logger=LOGGER):
            assert load_ruleset(path) is None
        assert "anchors and aliases" in caplog.text

    def test_a_malformed_cell_is_skipped_and_the_rest_load(self, tmp_path, caplog):
        path = tmp_path / "data_routing.yaml"
        path.write_text(
            f"version: {RULESET_VERSION}\n"
            "generated_at: '2026-09-09T12:00:00Z'\n"
            "cells:\n"
            "- key: {market: cn, asset_class: equity, surface: daily}\n"
            "  probed_at: '2026-09-09T12:00:00Z'\n"
            "  providers: [{name: tushare, coverage_hit: 1, coverage_total: 1}]\n"
            "- key: {market: us, asset_class: equity, surface: daily}\n"
            "  probed_at: yesterday\n"
            "- key: {market: hk, asset_class: equity, surface: snapshot}\n"
            "  probed_at: '2026-09-09T12:00:00Z'\n"
            "  providers: [{name: fmp, coverage_hit: 1, coverage_total: 1}]\n"
        )
        with caplog.at_level("WARNING", logger=LOGGER):
            loaded = load_ruleset(path)
        assert loaded is not None
        assert [c.key.as_str() for c in loaded.cells] == ["cn/equity/daily", "hk/equity/snapshot"]
        (record,) = caplog.records
        assert "data_routing.ruleset.cell_skipped" in record.getMessage()
        assert "key=us/equity/daily" in record.getMessage()
        table = RoutingTable(loaded)
        assert table.order_for("daily", "us", "equity") is None
        assert table.order_for("snapshot", "hk", "equity") == ["fmp"]

        # A writer merging into the file must not drop the cell it could not read.
        with pytest.raises(ValueError, match="us/equity/daily"):
            load_ruleset(path, strict=True)

    @pytest.mark.parametrize(
        "text",
        ["cells: [ this is not a ruleset\n", "version: 99\ngenerated_at: '2026-09-09T12:00:00Z'\n"],
        ids=["unreadable", "unknown-version"],
    )
    def test_strict_raises_for_a_file_a_writer_would_overwrite(self, tmp_path, text):
        # None would read as "no file yet", and the rewrite would start over.
        path = tmp_path / "data_routing.yaml"
        path.write_text(text)
        with pytest.raises(ValueError):
            load_ruleset(path, strict=True)

    def test_strict_is_none_only_when_absent(self, tmp_path):
        assert load_ruleset(tmp_path / "nope.yaml", strict=True) is None


@pytest.mark.parametrize(
    "surface,interval",
    [(Surface.INTRADAY, "ohlcv-1m"), (Surface.DAILY, None), (Surface.SNAPSHOT, None)],
)
def test_cell_key_as_str(surface, interval):
    key = CellKey(market="cn", asset_class="fund", surface=surface, interval=interval)
    tail = f"/{interval}" if interval else ""
    assert key.as_str() == f"cn/fund/{surface.value}{tail}"

