"""Writing a probe run into the deployment's ruleset file.

The protocol owns the schema and the loader; generating, merging and
fingerprinting are this tool's job.
"""

from __future__ import annotations

import hashlib
import os
import stat
import tempfile
from pathlib import Path
from typing import Optional

import yaml

from market_protocol.routing import (
    RULESET_VERSION,
    Cell,
    CellKey,
    Ruleset,
    load_ruleset,
    order_providers,
)

_HEADER = (
    "# Generated by `uv run python -m scripts.data_probe`. Do not edit by hand;\n"
    "# re-run the probe when a data subscription or token changes.\n"
)


def save_ruleset(ruleset: Ruleset, path: Path) -> Path:
    # A symlinked ruleset is replaced at its target, keeping the link (and
    # whatever points workers at it) intact.
    path = Path(os.path.realpath(path))
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        ruleset.model_dump(mode="json"), sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    # Workers may run as another user; mkstemp's 0600 would lock them out.
    try:
        mode = stat.S_IMODE(path.stat().st_mode)
    except FileNotFoundError:
        mode = 0o644
    # A worker may load the file at any moment; replace is atomic, truncate-then-write is not.
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(_HEADER + body)
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return path


def load_for_merge(path: Path) -> Optional[Ruleset]:
    """The ruleset a run merges into, refusing a file that exists but does not load whole.

    A worker reads past an unreadable file or cell so it keeps serving; a writer
    that did the same would replace what it skipped.
    """
    try:
        return load_ruleset(path, strict=True)
    except ValueError as exc:
        raise SystemExit(
            f"{exc}\nThat is not a ruleset this probe can read whole; fix or move "
            f"it before writing a probe run into it"
        ) from exc


def merge_rulesets(base: Optional[Ruleset], update: Ruleset) -> Ruleset:
    """Cell-by-cell, provider-by-provider merge.

    A provider *update* measured replaces its verdict in that cell; one only
    *base* measured keeps its own, so a run over some providers (``--provider``,
    or a token missing when it ran) cannot narrow a cell to them. Cells *update*
    did not touch survive whole: a CN-morning run and a US-afternoon run build
    one file.
    """
    if base is None:
        return update
    merged: dict[CellKey, Cell] = {c.key: c for c in base.cells}
    for c in update.cells:
        old = merged.get(c.key)
        if old is not None:
            measured = {p.name for p in c.providers}
            kept = [p for p in old.providers if p.name not in measured]
            c = c.model_copy(update={
                "providers": order_providers(c.key.surface, [*c.providers, *kept]),
            })
        merged[c.key] = c
    return Ruleset(
        version=RULESET_VERSION,
        generated_at=update.generated_at,
        probe_version=update.probe_version,
        providers={**base.providers, **update.providers},
        cells=list(merged.values()),
    )


def credential_fingerprint(secret: str | None) -> Optional[str]:
    """Short, non-reversible marker so a file can say which token it was probed with."""
    if not secret:
        return None
    return hashlib.sha256(secret.encode()).hexdigest()[:8]
